- Basic codes in Time Series Analysis
- Date format
- Lag operator
- Rolling
- Expanding

*IMPORTING PANDAS*

In [9]:
import pandas as pd

*IMPORTING FILE AND MAKING THE DATE COLUMN IN DATE FORMAT*
- 'pd.read_csv' to import
- 'parse_dates' to change into date format

In [13]:
series = pd.read_csv('daily-total-female-births-CA.csv',header=0,parse_dates=[0],index_col=0).squeeze()
series.head()
series.describe()

count    365.000000
mean      41.980822
std        7.348257
min       23.000000
25%       37.000000
50%       42.000000
75%       46.000000
max       73.000000
Name: births, dtype: float64

In [14]:
series.head()

date
1959-01-01    35
1959-01-02    32
1959-01-03    30
1959-01-04    31
1959-01-05    44
Name: births, dtype: int64

In [15]:
df = pd.read_csv('daily-total-female-births-CA.csv',header=0,parse_dates=[0])
df.head()

        date  births
0 1959-01-01      35
1 1959-01-02      32
2 1959-01-03      30
3 1959-01-04      31
4 1959-01-05      44

- [x] load data

**TO CREATE COLUMNS OF MONTH, YEAR AND DAY FROM THE DATE COLUMN**

In [18]:
df1 = df.copy()
df1['year']=df1['date'].dt.year
df1['month']=df1['date'].dt.month
df1['day']=df1['date'].dt.day
df1.head()

         date  births  year  month  day
0  1959-01-01      35  1959      1    1
1  1959-01-02      32  1959      1    2
2  1959-01-03      30  1959      1    3
3  1959-01-04      31  1959      1    4
4  1959-01-05      44  1959      1    5
..        ...     ...   ...    ...  ...
95 1959-04-06      33  1959      4    6
96 1959-04-07      35  1959      4    7
97 1959-04-08      38  1959      4    8
98 1959-04-09      38  1959      4    9
99 1959-04-10      34  1959      4   10

[100 rows x 5 columns]

- LAG OPERATOR USING 'shift()'
- WINDOW OPERATOR USING 'rolling(window = ).fn()
- 'expanding()' to compare the values upto that particular value

In [44]:
df1['lag1']=df1['births'].shift(1)
df1['lag365']=df1['births'].shift(365)
df1['Roll_mean']=df1['births'].rolling(window = 2).mean()
df1['Roll_max']=df1['births'].rolling(window = 2).max()
df1['Expanding_max']=df1['births'].expanding().max()

In [46]:
df1.head()

,date,births,year,month,day,lag1,lag365,Roll_mean,Roll_max,Expanding_max
0,1959-01-01,35,1959,1,1,NaN,NaN,NaN,NaN,35.0
1,1959-01-02,32,1959,1,2,35.0,NaN,33.5,35.0,35.0
2,1959-01-03,30,1959,1,3,32.0,NaN,31.0,32.0,35.0
3,1959-01-04,31,1959,1,4,30.0,NaN,30.5,31.0,35.0
4,1959-01-05,44,1959,1,5,31.0,NaN,37.5,44.0,44.0